"""Add referral_code table

Revision ID: 59bee92c6075
Revises: b87ee585a7b5
Create Date: 2023-04-13 16:55:35.707256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker

from api.models import ReferralCode, User
from api.users import generate_referral_code


# revision identifiers, used by Alembic.
revision = "59bee92c6075"
down_revision = "b87ee585a7b5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referral_code",
        sa.Column("id", sa.Integer(), nullable=False, comment="推荐码id"),
        sa.Column("code", sa.String(length=32), nullable=False, comment="推荐码"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="用户id"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("used_time", sa.DateTime(), nullable=True, comment="使用时间"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_referral_code_code"), "referral_code", ["code"], unique=True
    )

    with op.batch_alter_table("user") as batch_op:
        batch_op.add_column(sa.Column("used_referral_code", sa.Integer, nullable=True))
        batch_op.create_foreign_key(
            "fk_referral_code_code", "referral_code", ["used_referral_code"], ["code"]
        )

    # 获取数据库连接
    connection = op.get_bind()

    # 创建 Session
    Session = sessionmaker(bind=connection)
    session = Session()

    # 查询所有用户
    users = session.query(User).all()

    # 为每个用户创建推广码
    for user in users:
        referral_code = generate_referral_code()
        new_referral_code = ReferralCode(code=referral_code, user_id=user.id)
        session.add(new_referral_code)

    # 提交更改
    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user") as batch_op:
        batch_op.drop_constraint("fk_referral_code_code", type_="foreignkey")
        batch_op.drop_column("used_referral_code")

    op.drop_index(op.f("ix_referral_code_code"), table_name="referral_code")
    op.drop_table("referral_code")
    # ### end Alembic commands ###
