"""Add chatgpt_user table

Revision ID: 6014dec49e0a
Revises: 
Create Date: 2023-04-08 17:00:30.279073

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6014dec49e0a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chatgpt_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=64), nullable=False, comment="邮箱"),
        sa.Column(
            "hashed_password", sa.String(length=1024), nullable=False, comment="密码"
        ),
        sa.Column("is_plus", sa.Boolean(), nullable=False, comment="是否Plus用户"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="是否激活"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("access_token", sa.String(length=64), nullable=True, comment="访问令牌"),
        sa.Column(
            "access_token_refresh_time",
            sa.DateTime(),
            nullable=True,
            comment="访问令牌刷新时间",
        ),
        sa.Column("session_token", sa.String(length=64), nullable=True, comment="会话令牌"),
        sa.Column(
            "session_token_refresh_time",
            sa.DateTime(),
            nullable=True,
            comment="会话令牌刷新时间",
        ),
        sa.Column("puid", sa.String(length=64), nullable=True, comment="Plus用户cf标识"),
        sa.Column(
            "puid_refresh_time", sa.DateTime(), nullable=True, comment="puid刷新时间"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chatgpt_user_email"), "chatgpt_user", ["email"], unique=True
    )

    # change conversation table
    with op.batch_alter_table("conversation") as batch_op:
        batch_op.add_column(
            sa.Column(
                "chatgpt_user_id",
                sa.Integer(),
                nullable=True,
                comment="ChatGPT用户id",
            )
        )
        batch_op.create_foreign_key(
            "fk_chatgpt_user_id", "chatgpt_user", ["chatgpt_user_id"], ["id"]
        )

    # data
    connection = op.get_bind()
    metadata = sa.MetaData()
    metadata.reflect(bind=connection)

    chatgpt_user_table = sa.Table("chatgpt_user", metadata)
    op.execute(
        chatgpt_user_table.insert().values(
            id=1,
            email="aljeida@gmail.com",
            hashed_password="",
            is_plus=True,
            is_active=True,
            create_time=datetime.now(),
            access_token="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJhbGplaWRhQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS9hdXRoIjp7InVzZXJfaWQiOiJ1c2VyLWRuVVY2RXVUU25lN2M1amx2Q3JhQmsxQyJ9LCJpc3MiOiJodHRwczovL2F1dGgwLm9wZW5haS5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMDk4NTEwNjcxOTk1OTE4MTEwNDAiLCJhdWQiOlsiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MSIsImh0dHBzOi8vb3BlbmFpLm9wZW5haS5hdXRoMGFwcC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjgwODQ3MjQ4LCJleHAiOjE2ODIwNTY4NDgsImF6cCI6IlRkSkljYmUxNldvVEh0Tjk1bnl5d2g1RTR5T282SXRHIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBtb2RlbC5yZWFkIG1vZGVsLnJlcXVlc3Qgb3JnYW5pemF0aW9uLnJlYWQgb2ZmbGluZV9hY2Nlc3MifQ.OYF0aNCBV54KVLXHpgW8HnVgABTn7dTPmnY0d23uYSBiVDCyAE940kiMiVPHnOL2yOCK8SS0t1OnZTG4ZDkTRx6AVGn9QkT5BV38Q6sK6KyQSDC8HIr1BkQ4cTYkvDxsce2t1rjjW3geVEXyxFU275VTYFj2VKXkFOJ4N6SPCv4y4EA79Ia_5OAnmAURbj2aDCyN_KHp2Q4tIk_X3D0FAK4Ax4dXmyvqey65nwpAWWVq1WGOvoLCx6DDHN9unYPOYR9r63h9dYrF2LSYihQLxpDGkR0UnSWAWcyKvtx7C2_F3SlYvBHAAL_JK2o0PAXBFRpqyEi-SbEth-F1ePun_w",
            puid="user-dnUV6EuTSne7c5jlvCraBk1C:1680506810-uS3AysyKWwg6066sLmFFv0vculpUH9IdNWI%2BtHk2ZMM%3D",
        )
    )

    # get conversation table and update
    conversation_table = sa.Table("conversation", metadata)
    op.execute(
        conversation_table.update()
        .values(chatgpt_user_id=1)
    )
    connection.execute(sa.text("COMMIT;"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversation") as batch_op:
        # Drop the foreign key constraint
        batch_op.drop_constraint("fk_chatgpt_user_id", type_="foreignkey")
        batch_op.drop_column("chatgpt_user_id")

    op.drop_index(op.f("ix_chatgpt_user_email"), table_name="chatgpt_user")
    op.drop_table("chatgpt_user")
    # ### end Alembic commands ###
